:toc:
:toc-placement!:
:toclevels: 4
:imagesdir: https://raw.githubusercontent.com/lyrasis/dts-data-migration-docs/main/images

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= CollectionSpace data explainers

This documentation focuses in depth on how data behaves and can be used in CollectionSpace.

The primary audience for this documentation is folks at institutions migrating into CollectionSpace, who need to make informed decisions about how to migrate data into CS.

Information is added to this site in response to actual client questions in the process of Lyrasis custom migrations into CollectionSpace.

[IMPORTANT]
====
Since this documentation is being developed and primarily used in the context of custom migrations into Lyrasis-hosted CollectionSpace instances, some information here may be specific to Lyrasis' architecture and instance configuration setup.
====

== Other documentation and resources

* https://collectionspace.atlassian.net/wiki/spaces/CUD/overview[CollectionSpace User Manual] is more focused on how to use features of the web application.
* https://collectionspace.atlassian.net/wiki/spaces/CUD/pages/3435560961/CSV+Importer+Tool+Manual[CollectionSpace CSV Importer User Manual] focuses on how to use that tool

[IMPORTANT]
.*Access to the CollectionSpace User Manual is a benefit for contributors to the CollectionSpace program*
====
Instructions on how to request access to the User Manual, of which the CSV Importer Manual is a part, are https://collectionspace.atlassian.net/wiki/spaces/CO/pages/3480060370/Accessing+the+CollectionSpace+User+Manual[here].
====

* https://github.com/lyrasis/collectionspace-sql[collectionspace-sql Github repository] -- a collection of SQL queries and snippets, useful if you request read access to your database
