:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Object location, Location/movement/inventory (LMI) procedure, and Storage location authority

See also:

* xref:location_authority.adoc[Storage Location authority info and decisions]
* https://collectionspace.atlassian.net/wiki/spaces/COL/pages/536379393/CollectionSpace+User+Manual[CS User Manual]

toc::[]

== Key points

* Location information for an object is not recorded directly in the Object record.
* The Location/movement/inventory (LMI) procedure is used to record information about:
** the location of an object or objects
** if the location has changed, information about the movement of the object(s)
** if location is checked and recorded as part of an inventory task, information about the inventory
* Relationships must be created between the LMI procedure and the object(s) whose location it describes
* If an object is related to one or more LMI procedures, the current location field value from the most recent related LMI procedure is displayed in the object record as `Computed current location`. You can also search for objects by their `Computed current location` value.

== LMI location fields

These fields are populated with values from either of the Storage Location authorities (local or offsite), or the local Organization authority.

In the Public Art domain profile (and Fine and Contemporary Art starting with CS 7.2) you can also use terms from the local Place authority in these fields.

In the Botanical Garden domain profile, only terms from local Storage Location and local Organization authorities can be used.

NOTE: The sections below are titled using the underlying data field name, which is consistent across all domain profiles.

=== currentLocation

In general:

* This field is labeled: "Current location"
* This is a **required** field in the LMI procedure

Exceptions:

* Local history & material culture profile
** Labeled: "Temp location/building"
* Botanical garden profile
** Labeled: "Garden location"
** **Not a required field when manually entering records**

=== normalLocation

In general:

* This field is labeled: "Normal location"
* This is not a required field in the LMI procedure

Exceptions:

* Local history & material culture profile
** Labeled: "Home location/building"
* Botanical garden profile
** Not included
